version: '3'
services:
  metabase:
    build: .
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    restart: always